[package]
name = "rustymetrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = { version = "0.15", features = ["crossterm"] }
crossterm = "0.25"
sysinfo = "0.20"
battery = "0.7"



